spring:
  application:
    name: musicservice
  profiles:
    active: ${SPOTIFY_ACTIVE:dev-sam}
  config:
    import: "configserver:http://admin:1234@localhost:9000"

logging:
  level:
    org:
      hibernate: info

server:
  port: 9000

#    rabbitMQ
rabbitmq:
  exchange:
    name1: reviewExchange
  queue:
    q1: reviewq
  routing:
    topickey: review.#




