spring:
  application:
    name: bookservice
  profiles:
    active: ${SPOTIFY_ACTIVE:dev}
  config:
    import: "configserver:http://admin:1234@localhost:9000"

logging:
  level:
    org:
      hibernate: info
